# Generated by Django 3.2.6 on 2021-11-03 06:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('apiLink', models.TextField()),
                ('adddedOn', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default=None, max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('availability_status', models.BooleanField(default=True)),
                ('availability_notif_enabled', models.BooleanField(default=False)),
                ('price_notif_enabled', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_content', models.TextField()),
                ('notif_time', models.DateTimeField(auto_now_add=True)),
                ('assoc_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_notifs', to='shopBackend.item')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_log', models.CharField(max_length=511)),
                ('history_time', models.DateTimeField(auto_now_add=True)),
                ('history_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', ckeditor.fields.RichTextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('assoc_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_comments', to='shopBackend.item')),
            ],
        ),
    ]
