# Generated by Django 3.2.6 on 2021-11-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='normal', max_length=255),
        ),
    ]
