# Generated by Django 3.2.8 on 2021-10-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
