# Generated by Django 3.2.6 on 2021-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopBackend', '0003_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='history_log',
            field=models.TextField(),
        ),
    ]
