# Generated by Django 3.2.8 on 2021-11-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopBackend', '0004_alter_log_history_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_offers',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_schemes_notif_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExternalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_notif_content', models.TextField()),
                ('ext_notif_info', models.CharField(max_length=10)),
                ('assoc_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_external_notifs', to='shopBackend.item')),
            ],
        ),
    ]
