# Generated by Django 3.2.8 on 2021-11-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopBackend', '0005_auto_20211105_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
