# Generated by Django 3.2.8 on 2021-11-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopBackend', '0007_remove_item_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_time',
            field=models.DateTimeField(),
        ),
    ]
